[package]
name = "snips"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.0"
indoc = "1.0"
log = "0.4.14"
stderrlog = "0.5.1"
